apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: infinispan
spec:
  replicas: 1
  expose:
    type: Route
  security:
    endpointAuthentication: true
    endpointSecretName: infinispan-credentials
