apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: deploy-smart-log-analyzer-run-
spec:
  pipelineRef:
    name: deploy-smart-log-analyzer
  params:
    - name: namespace
      value: slog-analyzer
    - name: runtime
      value: quarkus
    - name: runtime-version
      value: "3.32.3"
