apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: generate-vault-token
spec:
  results:
    - name: token
      description: Randomly generated Vault root token
  steps:
    - name: generate
      image: registry.access.redhat.com/ubi9/ubi-minimal:latest
      script: |
        #!/usr/bin/env bash
        set -euo pipefail

        TOKEN=$(cat /proc/sys/kernel/random/uuid | tr -d '-')
        echo "Vault root token generated."
        printf '%s' "${TOKEN}" > "$(results.token.path)"
