apiVersion: v1
kind: ConfigMap
metadata:
  name: poll-source-repo-config
data:
  GITHUB_OWNER: "loop9x"
  GITHUB_REPO: "smart-log-analyzer"
  BRANCH: "main"
  REPO_URL: "https://github.com/loop9x/smart-log-analyzer.git"
  APP_ROOT: ""
  RUNTIME: "spring-boot"
  CAMEL_IMAGE: "quay.io/mcarlett/camel-launcher:4.18.0"
  CONFIG_REPO_URL: "https://github.com/mcarlett/smart-log-analyzer-ocp.git"
  CONFIG_REPO_REVISION: "gitops"
  DEPS: "camel:observability-services"
