apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: log-generator-instrumentation
spec:
  exporter:
    endpoint: http://camel-otel-collector-collector.camel-otel-infra.svc.cluster.local:4318
  propagators:
    - tracecontext
    - baggage
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
    env:
      - name: OTEL_SERVICE_NAME
        value: log-generator
      - name: OTEL_TRACES_EXPORTER
        value: otlp
      - name: OTEL_LOGS_EXPORTER
        value: otlp
      - name: OTEL_METRICS_EXPORTER
        value: none
