apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: deploy-log-generator-run-
spec:
  pipelineRef:
    name: deploy-log-generator
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
