infinispan.client.hotrod.security.ssl.trust_store_file_name=/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
infinispan.client.hotrod.security.ssl.trust_store_type=PEM
infinispan.client.hotrod.security.ssl.sni_host_name=infinispan.slog-analyzer.svc
