# Storage configuration
analyzer.storage.root=/tmp/analyzer-store

# JMS Queue configuration
camel.jms.queue.analysis-result=analysis-result

# Artemis JMS configuration for OpenShift
camel.beans.artemisCF = #class:org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory
camel.beans.artemisCF.brokerURL = ${ARTEMIS_BROKER_URL:tcp://artemis:61616}
camel.beans.artemisCF.user = {{hashicorp:secret:amq-username}}
camel.beans.artemisCF.password = {{hashicorp:secret:amq-password}}
camel.beans.poolCF = #class:org.messaginghub.pooled.jms.JmsPoolConnectionFactory
camel.beans.poolCF.connectionFactory = #bean:artemisCF
camel.beans.poolCF.maxSessionsPerConnection = 500
camel.beans.poolCF.connectionIdleTimeout = 20000
camel.component.jms.connection-factory = #bean:poolCF

# REST configuration
camel.rest.component=platform-http
camel.rest.binding-mode=off
camel.rest.port=8080
camel.rest.host=0.0.0.0

# Camel configuration
camel.main.name=ui-console

# Spring Boot HTTP configuration
server.port=8080
server.compression.enabled=true

# HashiCorp Vault configuration
camel.component.hashicorp-vault.early-resolve-properties=true
camel.vault.hashicorp.token=${HASHICORP_TOKEN}
camel.vault.hashicorp.host=${HASHICORP_HOST}
camel.vault.hashicorp.port=${HASHICORP_PORT}
camel.vault.hashicorp.scheme=http
