apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: slog-analyzer-pipeline
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: slog-analyzer
roleRef:
  kind: ClusterRole
  name: slog-analyzer-pipeline
  apiGroup: rbac.authorization.k8s.io
